version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: sipaling-db
    environment:
      POSTGRES_USER: ${DB_USER:-sipaling_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-sipaling_password}
      POSTGRES_DB: ${DB_NAME:-sipaling_db}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: sipaling-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin_user}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-admin_password}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data

  backend:
    build: .
    container_name: sipaling-backend
    restart: always
    environment:
      DATABASE_URL: postgres://${DB_USER:-sipaling_user}:${DB_PASSWORD:-sipaling_password}@db:5432/${DB_NAME:-sipaling_db}
      NODE_ENV: production
    env_file: .env
    depends_on:
      - db
      - minio
    ports:
      - "3000:3000"